// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evcpirjbklddgsuvstdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Y3Bpcmpia2xkZGdzdXZzdGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MDgxODcsImV4cCI6MjA1NjI4NDE4N30.s1Xp3BSJqEnl6ghI9BkyWEBkF7ZyQvWh-J5_IL-ovyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);